server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  # Config Server
  config:
    import: configserver:http://localhost:9296

  # Cloud Config (Gateway specific)
  cloud:
    gateway:
      routes:
        - id: VENDOR-SERVICE
          uri: http://localhost:8080 
          predicates:
            - Path=/vendor/**
          filters: # Config for Circuit Breaker
            - name: CircuitBreaker 
              args:
                name: VENDOR-SERVICE
                fallbackuri: forward:/vendorServiceFallBack
                # Rate Limiter Config
            - name: RequestRateLimiter 
              args: 
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        - id: USER-SERVICE
          uri: http://localhost:8081
          predicates:
            - Path=/user/**
          filters: # Config for Circuit Breaker
            - name: CircuitBreaker 
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
            - name: RequestRateLimiter
              args: 
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        - id: ADMIN-SERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/admin/**
          filters: # Config for Circuit Breaker
            - name: CircuitBreaker 
              args:
                name: ADMIN-SERVICE
                fallbackuri: forward:/adminServiceFallBack
            - name: RequestRateLimiter
              args: 
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1



# Zipkin Config
management:
    endpoints:
        web:
            exposure:
                include: "*"
    tracing: 
        sampling: 
            probability: 1.0


# Okta Config 
okta:
  oauth2:
    issuer: https://dev-90693819.okta.com/oauth2/default
    audience: api://default
    client-id: 0oab4phbjzZKmz9rl5d7
    client-secret: CYVlL38YWngew14V94x5XBOmMKtm61CBhby9P-qPGukFGmGFiWZKOEttXNTULfP8
    redirect-uri:   
    scopes: openid, profile, email, offline_access 